In [1]:
import numpy as np

In [5]:
# Finding inverse of the matrix
def inverse_of_transpose(matrix):
    # Transpose of  the matrix
    matrix_transpose = np.transpose(matrix)
    
    # Computing  the inverse of a matrix that is transposed .
    inverse_transpose = np.linalg.inv(matrix_transpose)
    
    return inverse_transpose

matrix = np.array([[1, 0.2, 0.5],
                    [0.2, 1, 0.8],
                    [0.5, 0.8, 1]])

# Calling the function to compute the inverse of the transposed matrix
result = inverse_of_transpose(matrix)

print("Original Matrix:")
print(matrix)
print("\nInverse of the Transpose:")
print(result)



Original Matrix:
[[1.  0.2 0.5]
 [0.2 1.  0.8]
 [0.5 0.8 1. ]]

Inverse of the Transpose:
[[ 1.56521739  0.86956522 -1.47826087]
 [ 0.86956522  3.26086957 -3.04347826]
 [-1.47826087 -3.04347826  4.17391304]]


In [12]:
#Determinant of the matrix
import numpy as np
def determinant(matrix):
    return np.linalg.det(matrix)
matrix = np.array([[1, 0.2, 0.5],
                [0.2, 1, 0.8],
                [0.5, 0.8, 1]])
determinant_value = determinant(matrix)
print(f"The Determinant of the matrix is: {det_value}")

The Determinant of the matrix is: 0.2299999999999999


In [10]:
import numpy as np

In [31]:
#decomposition of a matrix

matrix = np.array([
    [1, 0.2, 0.5],
    [0.2, 1, 0.8],
    [0.5,0.8,1]
])
L,U = lu_decomposition(matrix)
print("Original Matrix:")
print(matrix)
print("\nLower Triangular Matrix (L):")
print(L)
print("\nUpper Triangular Matrix (U):")
print(U)

# Verify that A = L * U
print("\nVerification: L * U =")
print(np.dot(L, U))


NameError: name 'lu_decomposition' is not defined

In [32]:
#d 
#matrix transpose
import numpy as np

In [35]:
def transformatio(matrix):
    return np.dot(matrix)
matrix = np.array([[1, 0.2, 0.5],
                [0.2, 1, 0.8],
                [0.5, 0.8, 1]])
transpose_matrix = transpose(matrix)
print(f"The transpose of the matrix is: {transpose_matrix}")

NameError: name 'transpose' is not defined