In [4]:
import numpy as np

In [5]:
#solving linear equations using matrices
#matrix addition
matrix1 = np.array([[1,2],[3,4]])
matrix2 = np.array([[5,6],[7,8]])
result = matrix1 + matrix2
print(result)

[[ 6  8]
 [10 12]]


In [6]:
#matrix multiplication
#define the matrices
matrix1 = np.array([[1,2],[3,4]])
matrix2 = np.array([[5,6],[7,8]])
#perform matrix multiplication
result = np.dot (matrix1 , matrix2)
print(result)

[[19 22]
 [43 50]]


In [7]:
#matrix division
# Creating the matrices
a = np.array([[4,6],[8,10]])
b = np.array([[2,3],[4,5]])
# Dividing matrices
result = np.divide(a,b)
print(result)

[[2. 2.]
 [2. 2.]]


In [9]:
#matrix subtraction
#creating matrices
matrix1 = np.array([[1,2,3],
                    [4,5,6]])
matrix2 = np.array([[7,8,9],
                     [10,11,12]])
# Perform element-wise subtraction
result_matrix = matrix1 - matrix2
print("Result of Element-wise subtraction:")
print(result_matrix)


Result of Element-wise subtraction:
[[-6 -6 -6]
 [-6 -6 -6]]
